name: CoinFlip
main: Bluxy\CoinFlip\CoinFlip
version: 1.0
api: 4.0.0
description: Simple CoinFlip Plugin For PMMP!
author: Bluxy

commands:
  coinflip:
    description: "Flips A Coin! returns heads or tails"
    permission: coinflip.flip
    usage: "/coinflip"

permissions:
  coinflip.flip:
    default: true